### ISSUE TITLE
error logs in console

### ISSUE THREAD

**Issue by linkinkov** [guipenedo/BungeePexBridge#2]
WARNING: Error dispatching event PermissionCheckEvent(sender=linkinkov, permission=wcnp.bypass, hasPermission=false) to listener me.philipsnostrum.bungeepexbridge.listener.PermissionCheckListener@31ff43be
java.lang.NullPointerException
	at me.philipsnostrum.bungeepexbridge.modules.PermPlayer.getPlayer(PermPlayer.java:37)
	at me.philipsnostrum.bungeepexbridge.BungeePexBridge.hasPermission(BungeePexBridge.java:194)
	at me.philipsnostrum.bungeepexbridge.listener.PermissionCheckListener.onPermissionCheck(PermissionCheckListener.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:377)
	at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:367)
	at com.gekatik.Event.playercmd(Event.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:377)
	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:110)
	at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:77)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:883)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:389)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:305)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at java.lang.Thread.run(Thread.java:745)

**Comment by linkinkov** [comment]
I am use SexyPex plugin too

**Comment by linkinkov** [comment]
All bungee permission dont work now :c

**Comment by linkinkov** [comment]
I found problem. In DB i have for user linkinkov group admin, on the server in file permissions.yml have:
  admin:
    inheritance:
    - premium
    permissions:
    - bungeepexbridge.reload
    - litebans.*
    - '*'
    options:
      prefix: '&f(&l&cАдмин&r&f)&r'

But permissions only read from DB, if i add permissions to DB all work great, but its ruine main feature of SexyPEX, then groups set in DB and permissions set in permissions.yml

Sorry for my english

**Comment by guipenedo** [comment]
Hi. Regarding sexypex, BPB only syncs groups to bungee. You should define your group permissions on bungee's config.yml. Read more here https://github.com/guipenedo/BungeePexBridge/wiki/Setup-for-SexyPex

**Comment by linkinkov** [comment]
Thanks a lot for answer! My mistake :c
