### ISSUE TITLE
error PEX

### ISSUE THREAD

**Issue by sadoj-kuro** [guipenedo/BungeePexBridge#7]
Hi i have a error with the pluging after config the mysql config etc 

`Exception encountered when loading plugin: BungeePexBridge 
java.lang.IllegalArgumentException: Can not set java.lang.String field me.philipsnostrum.bungeepexbridge.helpers.Config.mysql_user to java.lang.Long
    at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
    at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
    at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
    at java.lang.reflect.Field.set(Field.java:764)
    at me.philipsnostrum.bungeepexbridge.helpers.Config.<init>(Config.java:45)
    at me.philipsnostrum.bungeepexbridge.BungeePexBridge.onEnable(BungeePexBridge.java:55)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:273)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
`

here my config file
https://www.hastebin.com/rivulokila.py

**Comment by EmanYm** [comment]
PermissionsEx is kind of out dated and no longer developed.
Consider switching to [LuckPerms](https://github.com/lucko/LuckPerms)

**Comment by guipenedo** [comment]
Make sure you have ' around the username, database name, etc

**Comment by sadoj-kuro** [comment]
oh what now its working with ' before no :\ and thx pour luckperms i look that ^^
